apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gatsby-js-test
  description: Replace me with a real description.
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: your-team
